from __future__ import annotations

import csv
from datetime import date
from io import StringIO, BytesIO
from typing import Any
from flask import Blueprint, jsonify, request, render_template, session, send_file

from app.repositories.sales_repository import SalesRepository
from app.services.sales_service import SalesService
from app.utils.auth import login_required

sales_bp = Blueprint("sales_admin", __name__, url_prefix="/admin/daily-balance")

_service = SalesService(repo=SalesRepository())


@sales_bp.route("", methods=["GET"])
@login_required
def list_reports() -> str:
    reports = _service.list_reports()
    return render_template("admin/daily_balance.html", reports=reports)


@sales_bp.route("/api/reports", methods=["GET"])
@login_required
def api_list_reports() -> tuple:
    reports = _service.list_reports()
    return jsonify({"success": True, "data": reports}), 200


@sales_bp.route("/api/reports", methods=["POST"])
@login_required
def api_generate_report() -> tuple:
    data = request.get_json()
    report_date = date.fromisoformat(data.get("report_date"))
    result = _service.generate_report(
        report_date=report_date,
        generated_by=session.get("user_id"),
        notes=data.get("notes"),
    )
    return jsonify(result), 201


@sales_bp.route("/api/reports/export-csv", methods=["GET"])
@login_required
def api_export_csv() -> Any:
    reports = _service.list_reports()
    output = StringIO()
    writer = csv.DictWriter(
        output,
        fieldnames=[
            "Report Date",
            "Total Revenue",
            "Total Expenses",
            "Net Balance",
            "Total Orders",
            "Total Sessions",
            "Generated By",
            "Notes",
        ],
    )
    writer.writeheader()
    for report in reports:
        writer.writerow({
            "Report Date": report["report_date"],
            "Total Revenue": f"₱{report['total_revenue']:.2f}",
            "Total Expenses": f"₱{report['total_expenses']:.2f}",
            "Net Balance": f"₱{report['net_balance']:.2f}",
            "Total Orders": report["total_orders"],
            "Total Sessions": report["total_sessions"],
            "Generated By": report["generated_by"],
            "Notes": report["notes"] or "",
        })

    output.seek(0)
    bytes_output = BytesIO(output.getvalue().encode("utf-8"))
    return send_file(
        bytes_output,
        mimetype="text/csv",
        as_attachment=True,
        download_name="sales_report.csv",
    )